package com.moura1001.webForum.controller;

// Generated by Selenium IDE
import com.moura1001.webForum.model.infra.ConfigH2Database;
import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeAll;

public class ForumTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeAll
    public static void init() {
        ConfigH2Database.setupDatabase("src/main/resources/setup.sql", true);
    }

    @BeforeEach
    public void setUp() {
        setupGeckoDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    void setupGeckoDriver() {
        WebDriverManager.firefoxdriver().setup();
        driver = new FirefoxDriver();
        options();
    }

    private void options() {
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void deveCadastrarUmaContaParaUmUsuarioELogarNaNovaContaCriadaETerminarNaTelaDeTopicos() {
        driver.get("http://localhost:8080/web-forum-servlet-jsp-jdbc/");
        assertEquals("Fórum - Login", driver.getTitle());
        driver.findElement(By.id("btnCriarConta")).click();
        driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
        assertEquals("Fórum - Cadastro", driver.getTitle());
        driver.findElement(By.id("nome")).click();
        driver.findElement(By.id("nome")).sendKeys("Maria João");
        driver.findElement(By.id("login")).sendKeys("maria");
        driver.findElement(By.id("email")).sendKeys("maria@email.com");
        driver.findElement(By.id("senha")).sendKeys("456");
        driver.findElement(By.id("btnSubmit")).click();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        assertEquals("Fórum - Login", driver.getTitle());
        driver.findElement(By.id("login")).click();
        driver.findElement(By.id("login")).sendKeys("maria");
        driver.findElement(By.id("senha")).click();
        driver.findElement(By.id("senha")).sendKeys("456");
        driver.findElement(By.id("btnSubmit")).click();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        assertEquals("Fórum - Tópicos", driver.getTitle());
    }
}
